version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
       

#we are using the docker-compose up -d command because the d indicates detach mode meaning
#that adocker container runs in the background of your terminal, it doesnot receive input or 
#display output.