# Generated by Django 3.0 on 2022-04-22 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='custome name here', max_length=55)),
                ('phoneno', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 0706626855.upto 10digits allowed', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text=' email here', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='company name here', max_length=55)),
                ('email', models.EmailField(help_text='enter company email here', max_length=254)),
                ('phone_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 0706626855.upto 10digits allowed', regex='^\\+?1?\\d{9,10}$')])),
                ('logo', models.FileField(upload_to='')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('company_website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OurAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
