# Generated by Django 3.0 on 2022-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0006_client_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.URLField(null=True),
        ),
    ]
