# Generated by Django 3.0 on 2022-05-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0009_auto_20220511_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='location',
            new_name='countryLocation',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
    ]
