# Generated by Django 3.0 on 2022-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0010_auto_20220515_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='Elephant Plains', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='enter company email here', max_length=254, unique=True),
        ),
    ]
