# Generated by Django 3.0 on 2022-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0706626855', max_length=10, unique=True),
        ),
    ]
