# Generated by Django 3.0 on 2022-05-09 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allusers', '0006_client_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='category_name', max_length=55)),
                ('cat_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(help_text='property name here', max_length=55)),
                ('prop_image', models.FileField(upload_to='')),
                ('location', models.CharField(default='0', help_text='property location', max_length=55)),
                ('tour', models.URLField(default='https://my.matterport.com/show/?m=uAAJCS3gnPF')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('favs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category_name', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.Category')),
                ('company_name', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='company_propname', to='allusers.Company')),
                ('sub_user', models.ForeignKey(default='bosa', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_user', to='allusers.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='hotel  name here', max_length=55)),
                ('slug', models.SlugField(default='hotel', unique=True)),
                ('images', models.FileField(upload_to='')),
                ('description', models.TextField(help_text='enter the hotel descriptions here')),
                ('tour_link', models.URLField()),
                ('category_name', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_category', to='property.Category')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_hotel', to='allusers.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(help_text='appartment name here', max_length=55)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.FileField(upload_to='')),
                ('tour_link', models.URLField()),
                ('phone_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 0706626855.upto 10digits allowed', regex='^\\+?1?\\d{9,15}$')])),
                ('category_name', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='apart_category', to='property.Category')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_apartment', to='allusers.Company')),
            ],
        ),
    ]
