# Generated by Django 3.0 on 2022-04-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0002_auto_20220424_2054'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='company_name',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='company_propname', to='allusers.Company'),
        ),
    ]
