# Generated by Django 3.0 on 2022-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0006_client_location'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='sub_user',
        ),
        migrations.AddField(
            model_name='property',
            name='sub_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='properties_subscribed', to='allusers.Client'),
        ),
    ]
