# Generated by Django 3.0 on 2022-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0006_client_location'),
        ('property', '0002_auto_20220509_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sub_users',
            field=models.ManyToManyField(blank=True, related_name='properties_subscribed', to='allusers.Client'),
        ),
    ]
